sudo: false
language: java
dist: trusty
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
install: true
script: mvn clean package -P jacoco
after_success:
- bash <(curl -s https://codecov.io/bash)