codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  
ignore:
#generated
  - "src/main/java/xdean/jex/extra/collection/LinkedList.java"
  - "src/main/java/xdean/jex/extra/function/Action0.java"
  - "src/main/java/xdean/jex/extra/function/Action1.java"
  - "src/main/java/xdean/jex/extra/function/Action2.java"
  - "src/main/java/xdean/jex/extra/function/Func0.java"
  - "src/main/java/xdean/jex/extra/function/Func1.java"
  - "src/main/java/xdean/jex/extra/function/Func2.java"
  - "src/main/java/xdean/jex/extra/rx2/RxFunctions.java"
  - "src/main/java/xdean/jex/util/function/EmptyFunction.java"
  - "src/main/java/xdean/jex/util/function/FunctionAdapter.java"
  - "src/main/java/xdean/jex/util/reflect/model/GenericArrayTypeImpl.java"
  - "src/main/java/xdean/jex/util/reflect/model/ParameterizedTypeImpl.java"
  - "src/main/java/xdean/jex/util/reflect/model/WildcardTypeImpl.java"
  - "src/main/java/xdean/jex/util/TimingUtil.java"
#end
